### ISSUE TITLE
Maybe this comment is wrong

### ISSUE THREAD

**Issue by N1nt3n** [PacktPublishing/Linux-Device-Driver-Development-Second-Edition#3]
https://github.com/PacktPublishing/Linux-Device-Driver-Development-Second-Edition/blob/cd47b09275b85b4046b74d46af8d019eae9611d0/Chapter03/hr-timer.c#L26C36-L26C36

1 ms = 1 * 1000 * 1000 ns

**Comment by nithikpackt** [comment]
Hi @N1nt3n, I couldn't find this comment in the file you mentioned.
