### ISSUE TITLE
book errata

### ISSUE THREAD

**Issue by matthewconolly** [PacktPublishing/Linux-Device-Driver-Development-Second-Edition#4]
Page 30, second last paragraph
`$(CORSS_COMPILE) objdump` should be `$(CROSS_COMPILE) objdump`

**Comment by matthewconolly** [comment]
Page 69, code snippet
`#include<linux/workqueue.h>`
should be 
`#include <linux/workqueue.h>`

**Comment by nithikpackt** [comment]
Thank you for reporting these errata
